[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
arbitrage_program = ""

[programs.devnet]
arbitrage_program = ""

[provider]
cluster = ""
wallet = ""
url = ""

[provider.devnet]
cluster = "devnet"
wallet = ""
url = "https://api.devnet.solana.com"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
buffer_authority = ""
buffer_size = 300000
